### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [hendrimat/fyodor-dostoevsky_notes-from-the-underground#1]
- chapter-1-11 has a stray `<br>` at the end

- In poetry styling, a trailing <br> is not necessary, please remove those. For example chapter-2-8 line 33.

- The epigraph file has the part-1 section but it is actually under part-2. You can use the `recompose-epub` tool on this book, then open it in Firefox or Chrome dev tools to inspect the final tree it generates. 

- A half title is only necessary if there is front matter before the body matter. Since the "frontmatter" in this ebook is an epigraph to part 2, we don't actually need a half title. You can remove it and also remember to remove it from the ToC.

- Please add the style `[epub|type~="epigraph"] h2{ font-style: normal; }` so that the title in the epigraph is not italicized

**Comment by acabal** [comment]
Also:

- If the title of part 2 is "a propos of the wet snow", then that is the "subtitle" and should go in part-2.xhtml. In that case we are missing the subtitle of part 1, which according to the ToC in the page scans is "Underground". 

    The subtitle elements will go in the `<h2>` tag in part-*.xhtml.

- Because part-*.xhtml are at the `<h2>` level, that means that all children chapters must be `<h3>`. This can be fixed quickly with a project-wide find and replace.

**Comment by hendrimat** [comment]
- Should I remove the title of the epigraph?
- At the end of the epigraph "translated by Juliet Soskice" should actually be italicized and not in small caps. Should I leave it unchanged or make a CSS rule?

**Comment by acabal** [comment]
Yes, the title in epigraph.xhtml should be moved to part-2.xhtml as the subtitle of that `<h2>`. Therefore you can remove it from the epigraph completely. It is not the title of the epigraph.

You can leave the translator line as-is. Italics are not necessary.

**Comment by hendrimat** [comment]
Okay, I think it's finished then.

**Comment by acabal** [comment]
One last thing, I see you copied the long-description from Wikipedia. This is not allowed because Wikipedia is under a CC license but our work is released under a PD license. Can you please compose an original long description based on what you read? Typically the long description is an encyclopedia-like entry about the work, how it was composed, received, and its place in history. It is not a plot summary. Thanks!

**Comment by hendrimat** [comment]
Alright, I finished the long description, I hope it is suitable.
